/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analizadorlexico.View;

import analizadorlexico.Model.AFN;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel Morales
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    Dimension dimension;

    public mainView() {
        initComponents();
        int x, y;
        int WIDTH, HEIGHT;
        dimension = Toolkit.getDefaultToolkit().getScreenSize();
        WIDTH = (int) (dimension.getWidth() * 0.75);
        HEIGHT = (int) (dimension.getHeight() * 0.75);
        x = (int) ((dimension.getWidth() - WIDTH) / 2);
        y = (int) ((dimension.getHeight() - HEIGHT) / 2);
        setBounds(x, y, WIDTH, HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameAFNBasico = new javax.swing.JFrame();
        PanelAFNBasico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextCaracterInferior = new javax.swing.JTextField();
        TextCaracterSuperior = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextIDAFN = new javax.swing.JTextField();
        ButtonCrearAFN = new javax.swing.JButton();
        FrameAFNConcatenar = new javax.swing.JFrame();
        PanelAFNConcatenar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxConcatenar1 = new javax.swing.JComboBox<>();
        ComboBoxConcatenar2 = new javax.swing.JComboBox<>();
        ButtonConcatenarAFN = new javax.swing.JButton();
        FrameAFNCerraduraTransitiva = new javax.swing.JFrame();
        PanelAFNCerraduraTransitiva = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxCerraduraTransitiva = new javax.swing.JComboBox<>();
        ButtonCerraduraTransitivaAFN = new javax.swing.JButton();
        FrameAFNCerraduraKleen = new javax.swing.JFrame();
        PanelAFNCerraduraKleen = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxCerraduraKleen = new javax.swing.JComboBox<>();
        ButtonCerraduraKleenAFN = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        MenuAFN = new javax.swing.JMenu();
        MenuAFNBasico = new javax.swing.JMenuItem();
        MenuUnirAFNS = new javax.swing.JMenuItem();
        MenuConcatenarAFN = new javax.swing.JMenuItem();
        MenuCerraduraTransitivaAFN = new javax.swing.JMenuItem();
        MenuCerraduraKleen = new javax.swing.JMenuItem();
        MenuERaAFN = new javax.swing.JMenuItem();
        MenuUnion = new javax.swing.JMenuItem();
        MenuAFNaAFD = new javax.swing.JMenuItem();
        MenuAnalizarCadena = new javax.swing.JMenuItem();
        MenuAnalizadorLexico = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        FrameAFNBasico.setTitle("Creacion de AFN Basico");
        FrameAFNBasico.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FrameAFNBasicoWindowClosing(evt);
            }
        });

        jLabel1.setText("Caracter Inferior: ");
        jLabel1.setInheritsPopupMenu(false);

        jLabel2.setText("Caracter Superior: ");

        TextCaracterInferior.setColumns(1);
        TextCaracterInferior.setToolTipText("");
        TextCaracterInferior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCaracterInferiorKeyTyped(evt);
            }
        });

        TextCaracterSuperior.setColumns(1);
        TextCaracterSuperior.setToolTipText("");
        TextCaracterSuperior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCaracterSuperiorKeyTyped(evt);
            }
        });

        jLabel3.setText("Id AFN");

        TextIDAFN.setColumns(1);
        TextIDAFN.setToolTipText("");
        TextIDAFN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextIDAFNKeyTyped(evt);
            }
        });

        ButtonCrearAFN.setText("Crear AFN");
        ButtonCrearAFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonCrearAFNMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelAFNBasicoLayout = new javax.swing.GroupLayout(PanelAFNBasico);
        PanelAFNBasico.setLayout(PanelAFNBasicoLayout);
        PanelAFNBasicoLayout.setHorizontalGroup(
            PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAFNBasicoLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelAFNBasicoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)))
                .addGap(18, 18, 18)
                .addGroup(PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCrearAFN, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(TextCaracterInferior)
                    .addComponent(TextCaracterSuperior)
                    .addComponent(TextIDAFN))
                .addGap(122, 122, 122))
        );
        PanelAFNBasicoLayout.setVerticalGroup(
            PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAFNBasicoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextCaracterInferior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextCaracterSuperior))
                .addGap(55, 55, 55)
                .addGroup(PanelAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIDAFN))
                .addGap(57, 57, 57)
                .addComponent(ButtonCrearAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout FrameAFNBasicoLayout = new javax.swing.GroupLayout(FrameAFNBasico.getContentPane());
        FrameAFNBasico.getContentPane().setLayout(FrameAFNBasicoLayout);
        FrameAFNBasicoLayout.setHorizontalGroup(
            FrameAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNBasicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNBasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameAFNBasicoLayout.setVerticalGroup(
            FrameAFNBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNBasicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNBasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        FrameAFNConcatenar.setTitle("Concatenacion de AFNS");
        FrameAFNConcatenar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FrameAFNConcatenarWindowClosing(evt);
            }
        });

        jLabel4.setText("Concatenar AFN: ");
        jLabel4.setInheritsPopupMenu(false);

        jLabel5.setText("Con AFN:");

        ComboBoxConcatenar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboBoxConcatenar1MousePressed(evt);
            }
        });

        ComboBoxConcatenar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboBoxConcatenar2MousePressed(evt);
            }
        });

        ButtonConcatenarAFN.setText("Concatenar AFN'S");
        ButtonConcatenarAFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonConcatenarAFNMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelAFNConcatenarLayout = new javax.swing.GroupLayout(PanelAFNConcatenar);
        PanelAFNConcatenar.setLayout(PanelAFNConcatenarLayout);
        PanelAFNConcatenarLayout.setHorizontalGroup(
            PanelAFNConcatenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAFNConcatenarLayout.createSequentialGroup()
                .addGroup(PanelAFNConcatenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAFNConcatenarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonConcatenarAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAFNConcatenarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxConcatenar1, 0, 80, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxConcatenar2, 0, 80, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );
        PanelAFNConcatenarLayout.setVerticalGroup(
            PanelAFNConcatenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAFNConcatenarLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(PanelAFNConcatenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxConcatenar1)
                    .addComponent(ComboBoxConcatenar2))
                .addGap(52, 52, 52)
                .addComponent(ButtonConcatenarAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout FrameAFNConcatenarLayout = new javax.swing.GroupLayout(FrameAFNConcatenar.getContentPane());
        FrameAFNConcatenar.getContentPane().setLayout(FrameAFNConcatenarLayout);
        FrameAFNConcatenarLayout.setHorizontalGroup(
            FrameAFNConcatenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNConcatenarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNConcatenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameAFNConcatenarLayout.setVerticalGroup(
            FrameAFNConcatenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNConcatenarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNConcatenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        FrameAFNCerraduraTransitiva.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FrameAFNCerraduraTransitiva.setTitle("Cerradura Transitiva");
        FrameAFNCerraduraTransitiva.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FrameAFNCerraduraTransitivaWindowClosing(evt);
            }
        });

        jLabel6.setText("Aplicar cerradura transitiva a: ");
        jLabel6.setInheritsPopupMenu(false);

        ComboBoxCerraduraTransitiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboBoxCerraduraTransitivaMousePressed(evt);
            }
        });

        ButtonCerraduraTransitivaAFN.setText("Relizar operacion +");
        ButtonCerraduraTransitivaAFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonCerraduraTransitivaAFNMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelAFNCerraduraTransitivaLayout = new javax.swing.GroupLayout(PanelAFNCerraduraTransitiva);
        PanelAFNCerraduraTransitiva.setLayout(PanelAFNCerraduraTransitivaLayout);
        PanelAFNCerraduraTransitivaLayout.setHorizontalGroup(
            PanelAFNCerraduraTransitivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAFNCerraduraTransitivaLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addComponent(ComboBoxCerraduraTransitiva, 0, 80, Short.MAX_VALUE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAFNCerraduraTransitivaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCerraduraTransitivaAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        PanelAFNCerraduraTransitivaLayout.setVerticalGroup(
            PanelAFNCerraduraTransitivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAFNCerraduraTransitivaLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(PanelAFNCerraduraTransitivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxCerraduraTransitiva))
                .addGap(49, 49, 49)
                .addComponent(ButtonCerraduraTransitivaAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout FrameAFNCerraduraTransitivaLayout = new javax.swing.GroupLayout(FrameAFNCerraduraTransitiva.getContentPane());
        FrameAFNCerraduraTransitiva.getContentPane().setLayout(FrameAFNCerraduraTransitivaLayout);
        FrameAFNCerraduraTransitivaLayout.setHorizontalGroup(
            FrameAFNCerraduraTransitivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNCerraduraTransitivaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNCerraduraTransitiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameAFNCerraduraTransitivaLayout.setVerticalGroup(
            FrameAFNCerraduraTransitivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNCerraduraTransitivaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNCerraduraTransitiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        FrameAFNCerraduraKleen.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        FrameAFNCerraduraKleen.setTitle("Cerradura de kleen");
        FrameAFNCerraduraKleen.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FrameAFNCerraduraKleenWindowClosing(evt);
            }
        });

        jLabel7.setText("Aplicar cerradura kleen a: ");
        jLabel7.setInheritsPopupMenu(false);

        ComboBoxCerraduraKleen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboBoxCerraduraKleenMousePressed(evt);
            }
        });

        ButtonCerraduraKleenAFN.setText("Realizar Operacion *");
        ButtonCerraduraKleenAFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonCerraduraKleenAFNMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelAFNCerraduraKleenLayout = new javax.swing.GroupLayout(PanelAFNCerraduraKleen);
        PanelAFNCerraduraKleen.setLayout(PanelAFNCerraduraKleenLayout);
        PanelAFNCerraduraKleenLayout.setHorizontalGroup(
            PanelAFNCerraduraKleenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAFNCerraduraKleenLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(ComboBoxCerraduraKleen, 0, 100, Short.MAX_VALUE)
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAFNCerraduraKleenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCerraduraKleenAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        PanelAFNCerraduraKleenLayout.setVerticalGroup(
            PanelAFNCerraduraKleenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAFNCerraduraKleenLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(PanelAFNCerraduraKleenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxCerraduraKleen))
                .addGap(49, 49, 49)
                .addComponent(ButtonCerraduraKleenAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout FrameAFNCerraduraKleenLayout = new javax.swing.GroupLayout(FrameAFNCerraduraKleen.getContentPane());
        FrameAFNCerraduraKleen.getContentPane().setLayout(FrameAFNCerraduraKleenLayout);
        FrameAFNCerraduraKleenLayout.setHorizontalGroup(
            FrameAFNCerraduraKleenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNCerraduraKleenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNCerraduraKleen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameAFNCerraduraKleenLayout.setVerticalGroup(
            FrameAFNCerraduraKleenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAFNCerraduraKleenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAFNCerraduraKleen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compiladores");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setName("mainViewFrame"); // NOI18N

        MenuAFN.setText("AFN");

        MenuAFNBasico.setText("AFN Basico");
        MenuAFNBasico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuAFNBasicoMousePressed(evt);
            }
        });
        MenuAFN.add(MenuAFNBasico);

        MenuUnirAFNS.setText("Unir AFN'S");
        MenuAFN.add(MenuUnirAFNS);

        MenuConcatenarAFN.setText("Concatenar AFN'S");
        MenuConcatenarAFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuConcatenarAFNMousePressed(evt);
            }
        });
        MenuAFN.add(MenuConcatenarAFN);

        MenuCerraduraTransitivaAFN.setText("Cerradura Transitiva AFN'S");
        MenuCerraduraTransitivaAFN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuCerraduraTransitivaAFNMousePressed(evt);
            }
        });
        MenuAFN.add(MenuCerraduraTransitivaAFN);

        MenuCerraduraKleen.setText("Cerradura Kleen AFN'S");
        MenuCerraduraKleen.setToolTipText("");
        MenuAFN.add(MenuCerraduraKleen);

        MenuERaAFN.setText("ER a AFN");
        MenuAFN.add(MenuERaAFN);

        MenuUnion.setText("Union");
        MenuAFN.add(MenuUnion);

        MenuAFNaAFD.setText("Convertir AFN a AFD");
        MenuAFN.add(MenuAFNaAFD);

        MenuAnalizarCadena.setText("Analizar una cadena");
        MenuAFN.add(MenuAnalizarCadena);

        MenuAnalizadorLexico.setText("Analizador Lexico");
        MenuAFN.add(MenuAnalizadorLexico);

        MenuBar.add(MenuAFN);

        jMenu3.setText("Edit");
        MenuBar.add(jMenu3);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAFNBasicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAFNBasicoMousePressed
        // TODO add your handling code here:
        int x, y;
        int WIDTH, HEIGHT;
        WIDTH = (int) (dimension.getWidth() * 0.50);
        HEIGHT = (int) (dimension.getHeight() * 0.50);
        x = (int) ((dimension.getWidth() - WIDTH) / 2);
        y = (int) ((dimension.getHeight() - HEIGHT) / 2);
        FrameAFNBasico.setBounds(x, y, WIDTH, HEIGHT);
        TextCaracterInferior.setText("");
        TextCaracterSuperior.setText("");
        TextIDAFN.setText("");
        FrameAFNBasico.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuAFNBasicoMousePressed

    private void FrameAFNBasicoWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrameAFNBasicoWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_FrameAFNBasicoWindowClosing

    private void TextCaracterInferiorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCaracterInferiorKeyTyped
        // TODO add your handling code here:
        if (TextCaracterInferior.getText().length() >= 1) {
            TextCaracterInferior.setText(TextCaracterInferior.getText().substring(0, 0));
        }
    }//GEN-LAST:event_TextCaracterInferiorKeyTyped

    private void TextCaracterSuperiorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCaracterSuperiorKeyTyped
        // TODO add your handling code here:
        if (TextCaracterSuperior.getText().length() >= 1) {
            TextCaracterSuperior.setText(TextCaracterSuperior.getText().substring(0, 0));
        }
    }//GEN-LAST:event_TextCaracterSuperiorKeyTyped

    private void TextIDAFNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextIDAFNKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == evt.VK_BACK_SPACE)
                || (c == evt.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TextIDAFNKeyTyped

    private void ButtonCrearAFNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCrearAFNMousePressed
        // TODO add your handling code here:
        AFN afn = new AFN();
        Optional<AFN> op = AFN.conjuntoAFN.stream().filter(tmp -> tmp.idAFN == Integer.parseInt(TextIDAFN.getText())).findFirst();
        if (!op.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Id ya existe.", "ERROR", JOptionPane.OK_OPTION);
        } else {
            afn.setIdAFN(Integer.parseInt(TextIDAFN.getText()));
            AFN.conjuntoAFN.add(afn.CrearAFNBasico(TextCaracterInferior.getText().charAt(0), TextCaracterSuperior.getText().charAt(0)));
            for (AFN item : AFN.conjuntoAFN) {
                System.out.println("Valor: " + "Id: " + item.getIdAFN() + "" + item.estadosAFN.toString());
            }
            JOptionPane.showMessageDialog(this, "Creacion Correcta del AFN.", "Exito", JOptionPane.WARNING_MESSAGE);
            System.out.println("Vamos a crear AFN");
            FrameAFNBasico.dispose();
            this.setVisible(true);
        }

    }//GEN-LAST:event_ButtonCrearAFNMousePressed

    private void FrameAFNConcatenarWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrameAFNConcatenarWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_FrameAFNConcatenarWindowClosing

    private void MenuConcatenarAFNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuConcatenarAFNMousePressed
        // TODO add your handling code here:
        int x, y;
        int WIDTH, HEIGHT;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        ComboBoxConcatenar1.setModel(model);
        DefaultComboBoxModel mode2 = new DefaultComboBoxModel();
        mode2.removeAllElements();
        ComboBoxConcatenar2.setModel(mode2);
        WIDTH = (int) (dimension.getWidth() * 0.50);
        HEIGHT = (int) (dimension.getHeight() * 0.50);
        x = (int) ((dimension.getWidth() - WIDTH) / 2);
        y = (int) ((dimension.getHeight() - HEIGHT) / 2);
        FrameAFNConcatenar.setBounds(x, y, WIDTH, HEIGHT);
        FrameAFNConcatenar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuConcatenarAFNMousePressed

    private void ButtonConcatenarAFNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConcatenarAFNMousePressed
        // TODO add your handling code here:
        String[] r = ComboBoxConcatenar1.getSelectedItem().toString().split(" ");
        String[] r2 = ComboBoxConcatenar2.getSelectedItem().toString().split(" ");
        Optional<AFN> op = AFN.conjuntoAFN.stream().filter(tmp -> tmp.idAFN == Integer.parseInt(r[2])).findFirst();
        Optional<AFN> op2 = AFN.conjuntoAFN.stream().filter(tmp -> tmp.idAFN == Integer.parseInt(r2[2])).findFirst();
        AFN.conjuntoAFN.remove(op.get());
        AFN.conjuntoAFN.remove(op2.get());
        AFN afn1 = op.get();
        AFN afn2 = op2.get();
        System.out.println("AFN 1 a concatenar: " + afn1.estadosAFN.toString());
        System.out.println("AFN 2 a concatenar: " + afn2.estadosAFN.toString());
        afn1.ConcatenacionAFN(afn2);
        AFN.conjuntoAFN.add(afn1);
        System.out.println("Se concatenaron...  ");
//        for (AFN item : AFN.conjuntoAFN) {
//            System.out.println("Valor: " + "Id: " + item.getIdAFN() + "" + item.estadosAFN.toString());
//        }
        FrameAFNConcatenar.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_ButtonConcatenarAFNMousePressed

    private void ComboBoxConcatenar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxConcatenar1MousePressed
        // TODO add your handling code here:

        DefaultComboBoxModel model = (DefaultComboBoxModel) ComboBoxConcatenar1.getModel();
        model.removeAllElements();
        for (AFN item : AFN.conjuntoAFN) {
            model.addElement("Id AFN: " + item.getIdAFN());
        }
        ComboBoxConcatenar1.setModel(model);
    }//GEN-LAST:event_ComboBoxConcatenar1MousePressed

    private void ComboBoxConcatenar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxConcatenar2MousePressed
        // TODO add your handling code here:
        DefaultComboBoxModel model = (DefaultComboBoxModel) ComboBoxConcatenar2.getModel();
        model.removeAllElements();
        for (AFN item : AFN.conjuntoAFN) {
            model.addElement("Id AFN: " + item.getIdAFN());
        }
        ComboBoxConcatenar2.setModel(model);
    }//GEN-LAST:event_ComboBoxConcatenar2MousePressed

    private void ComboBoxCerraduraTransitivaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxCerraduraTransitivaMousePressed
        // TODO add your handling code here:
        DefaultComboBoxModel model = (DefaultComboBoxModel) ComboBoxCerraduraTransitiva.getModel();
        model.removeAllElements();
        for (AFN item : AFN.conjuntoAFN) {
            model.addElement("Id AFN: " + item.getIdAFN());
        }
        ComboBoxCerraduraTransitiva.setModel(model);
    }//GEN-LAST:event_ComboBoxCerraduraTransitivaMousePressed

    private void ButtonCerraduraTransitivaAFNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCerraduraTransitivaAFNMousePressed
        // TODO add your handling code here:
        String[] r = ComboBoxCerraduraTransitiva.getSelectedItem().toString().split(" ");
        Optional<AFN> op = AFN.conjuntoAFN.stream().filter(tmp -> tmp.idAFN == Integer.parseInt(r[2])).findFirst();
        AFN.conjuntoAFN.remove(op.get());
        AFN afn1 = op.get();
        System.out.println("AFN 1 se aplica cerradura transitiva: " + afn1.estadosAFN.toString());
        afn1.CerraduraPos();
        AFN.conjuntoAFN.add(afn1);
        System.out.println("Se aplico cerradura transitiva...");
//        for (AFN item : AFN.conjuntoAFN) {
//            System.out.println("Valor: " + "Id: " + item.getIdAFN() + "" + item.estadosAFN.toString());
//        }
        FrameAFNCerraduraTransitiva.dispose();
        this.setVisible(true);

    }//GEN-LAST:event_ButtonCerraduraTransitivaAFNMousePressed

    private void FrameAFNCerraduraTransitivaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrameAFNCerraduraTransitivaWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_FrameAFNCerraduraTransitivaWindowClosing

    private void MenuCerraduraTransitivaAFNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCerraduraTransitivaAFNMousePressed
        // TODO add your handling code here:
        int x, y;
        int WIDTH, HEIGHT;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        ComboBoxCerraduraTransitiva.setModel(model);
        WIDTH = (int) (dimension.getWidth() * 0.50);
        HEIGHT = (int) (dimension.getHeight() * 0.50);
        x = (int) ((dimension.getWidth() - WIDTH) / 2);
        y = (int) ((dimension.getHeight() - HEIGHT) / 2);
        FrameAFNCerraduraTransitiva.setBounds(x, y, WIDTH, HEIGHT);
        FrameAFNCerraduraTransitiva.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCerraduraTransitivaAFNMousePressed

    private void ComboBoxCerraduraKleenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxCerraduraKleenMousePressed
        // TODO add your handling code here:
        DefaultComboBoxModel model = (DefaultComboBoxModel) ComboBoxCerraduraKleen.getModel();
        model.removeAllElements();
        for (AFN item : AFN.conjuntoAFN) {
            model.addElement("Id AFN: " + item.getIdAFN());
        }
        ComboBoxCerraduraKleen.setModel(model);
    }//GEN-LAST:event_ComboBoxCerraduraKleenMousePressed

    private void ButtonCerraduraKleenAFNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCerraduraKleenAFNMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCerraduraKleenAFNMousePressed

    private void FrameAFNCerraduraKleenWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrameAFNCerraduraKleenWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_FrameAFNCerraduraKleenWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCerraduraKleenAFN;
    private javax.swing.JButton ButtonCerraduraTransitivaAFN;
    private javax.swing.JButton ButtonConcatenarAFN;
    private javax.swing.JButton ButtonCrearAFN;
    private javax.swing.JComboBox<String> ComboBoxCerraduraKleen;
    private javax.swing.JComboBox<String> ComboBoxCerraduraTransitiva;
    private javax.swing.JComboBox<String> ComboBoxConcatenar1;
    private javax.swing.JComboBox<String> ComboBoxConcatenar2;
    private javax.swing.JFrame FrameAFNBasico;
    private javax.swing.JFrame FrameAFNCerraduraKleen;
    private javax.swing.JFrame FrameAFNCerraduraTransitiva;
    private javax.swing.JFrame FrameAFNConcatenar;
    private javax.swing.JMenu MenuAFN;
    private javax.swing.JMenuItem MenuAFNBasico;
    private javax.swing.JMenuItem MenuAFNaAFD;
    private javax.swing.JMenuItem MenuAnalizadorLexico;
    private javax.swing.JMenuItem MenuAnalizarCadena;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuCerraduraKleen;
    private javax.swing.JMenuItem MenuCerraduraTransitivaAFN;
    private javax.swing.JMenuItem MenuConcatenarAFN;
    private javax.swing.JMenuItem MenuERaAFN;
    private javax.swing.JMenuItem MenuUnion;
    private javax.swing.JMenuItem MenuUnirAFNS;
    private javax.swing.JPanel PanelAFNBasico;
    private javax.swing.JPanel PanelAFNCerraduraKleen;
    private javax.swing.JPanel PanelAFNCerraduraTransitiva;
    private javax.swing.JPanel PanelAFNConcatenar;
    private javax.swing.JTextField TextCaracterInferior;
    private javax.swing.JTextField TextCaracterSuperior;
    private javax.swing.JTextField TextIDAFN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    // End of variables declaration//GEN-END:variables
}
